apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: sukus-patient-visit-be-mongodb-init
    files:
      - params/init-db.js
  - name: sukus-patient-visit-be-config
    literals:
      - database=sukus-patient-visit
patches:
- path: patches/webapi.deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: sukus-patient-visit-be
