/*
 * Patient Visit API
 *
 * Patient Visit Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package patient_visit

import (
	"github.com/gin-gonic/gin"
)

type PatientVisitsAPI interface {


    // CreatePatientVisit Post /api/patient-visits
    // Create new patient visit 
     CreatePatientVisit(c *gin.Context)

    // DeletePatientVisit Delete /api/patient-visits/:id
    // Delete patient visit 
     DeletePatientVisit(c *gin.Context)

    // GetPatientVisit Get /api/patient-visits/:id
    // Get patient visit by ID 
     GetPatientVisit(c *gin.Context)

    // GetPatientVisits Get /api/patient-visits
    // Get all patient visits (admin / filtered) 
     GetPatientVisits(c *gin.Context)

    // UpdatePatientVisit Put /api/patient-visits/:id
    // Update patient visit 
     UpdatePatientVisit(c *gin.Context)

}