/*
 * Patient Visit API
 *
 * Patient Visit Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package patient_visit

import (
	"github.com/gin-gonic/gin"
)

type PatientsAPI interface {


    // GetPatient Get /api/patients/:id
    // Get patient by ID 
     GetPatient(c *gin.Context)

    // GetPatientVisitsByPatient Get /api/patients/:id/visits
    // Get visits for a specific patient 
     GetPatientVisitsByPatient(c *gin.Context)

    // GetPatients Get /api/patients
    // Get all patients 
     GetPatients(c *gin.Context)

}