/*
 * Patient Visit API
 *
 * Patient Visit Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package patient_visit

import (
	"github.com/gin-gonic/gin"
)

type DoctorsAPI interface {


    // GetDoctor Get /api/doctors/:id
    // Get doctor by ID 
     GetDoctor(c *gin.Context)

    // GetDoctors Get /api/doctors
    // Get all doctors 
     GetDoctors(c *gin.Context)

    // GetPatientVisitsByDoctor Get /api/doctors/:id/visits
    // Get visits for a specific doctor 
     GetPatientVisitsByDoctor(c *gin.Context)

}