/*
 * Patient Visit API
 *
 * Patient Visit Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package patient_visit

import (
	"time"
)

type PatientVisit struct {

	Id string `json:"id,omitempty"`

	PatientId string `json:"patientId,omitempty"`

	PatientName string `json:"patientName,omitempty"`

	DoctorId string `json:"doctorId,omitempty"`

	DoctorName string `json:"doctorName,omitempty"`

	VisitDate time.Time `json:"visitDate,omitempty"`

	Anamnesis string `json:"anamnesis,omitempty"`

	Findings string `json:"findings,omitempty"`

	Conclusion string `json:"conclusion,omitempty"`

	Notes string `json:"notes,omitempty"`

	Status VisitStatus `json:"status,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
