/*
 * Patient Visit API
 *
 * Patient Visit Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package patient_visit

import (
	"time"
)

type PatientVisitCreateUpdate struct {

	PatientId string `json:"patientId"`

	DoctorId string `json:"doctorId"`

	VisitDate time.Time `json:"visitDate"`

	Anamnesis string `json:"anamnesis,omitempty"`

	Findings string `json:"findings,omitempty"`

	Conclusion string `json:"conclusion,omitempty"`

	Notes string `json:"notes,omitempty"`

	Status VisitStatus `json:"status"`
}
