/*
 * Patient Visit API
 *
 * Patient Visit Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package patient_visit

type VisitStatus string

// List of VisitStatus
const (
	CLOSED VisitStatus = "closed"
	OPEN VisitStatus = "open"
	ARCHIVED VisitStatus = "archived"
	DELETED VisitStatus = "deleted"
)
