/*
 * Patient Visit API
 *
 * Patient Visit Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package patient_visit

type Role string

// List of Role
const (
	DOCTOR Role = "doctor"
	PATIENT Role = "patient"
	ADMIN Role = "admin"
)
