/*
 * Patient Visit API
 *
 * Patient Visit Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package patient_visit

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the DoctorsAPI part of the API
	DoctorsAPI DoctorsAPI
	// Routes for the PatientVisitsAPI part of the API
	PatientVisitsAPI PatientVisitsAPI
	// Routes for the PatientsAPI part of the API
	PatientsAPI PatientsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"GetDoctor",
			http.MethodGet,
			"/api/doctors/:id",
			handleFunctions.DoctorsAPI.GetDoctor,
		},
		{
			"GetDoctors",
			http.MethodGet,
			"/api/doctors",
			handleFunctions.DoctorsAPI.GetDoctors,
		},
		{
			"GetPatientVisitsByDoctor",
			http.MethodGet,
			"/api/doctors/:id/visits",
			handleFunctions.DoctorsAPI.GetPatientVisitsByDoctor,
		},
		{
			"CreatePatientVisit",
			http.MethodPost,
			"/api/patient-visits",
			handleFunctions.PatientVisitsAPI.CreatePatientVisit,
		},
		{
			"DeletePatientVisit",
			http.MethodDelete,
			"/api/patient-visits/:id",
			handleFunctions.PatientVisitsAPI.DeletePatientVisit,
		},
		{
			"GetPatientVisit",
			http.MethodGet,
			"/api/patient-visits/:id",
			handleFunctions.PatientVisitsAPI.GetPatientVisit,
		},
		{
			"GetPatientVisits",
			http.MethodGet,
			"/api/patient-visits",
			handleFunctions.PatientVisitsAPI.GetPatientVisits,
		},
		{
			"UpdatePatientVisit",
			http.MethodPut,
			"/api/patient-visits/:id",
			handleFunctions.PatientVisitsAPI.UpdatePatientVisit,
		},
		{
			"GetPatient",
			http.MethodGet,
			"/api/patients/:id",
			handleFunctions.PatientsAPI.GetPatient,
		},
		{
			"GetPatientVisitsByPatient",
			http.MethodGet,
			"/api/patients/:id/visits",
			handleFunctions.PatientsAPI.GetPatientVisitsByPatient,
		},
		{
			"GetPatients",
			http.MethodGet,
			"/api/patients",
			handleFunctions.PatientsAPI.GetPatients,
		},
	}
}
